---
check_interval: 15m
messenger:
  type: telegram
  token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  chatid: 123456789
storage:
  type: memory
  cooldown_duration: 60m
logger:
  format: plaintext
  level: info
alerts:
- name: Ping google.com
  command: netPingHost.sh
  params:
    - google.com
- name: Resolve DNS-name google.com
  command: netDnsCheck.sh
  params:
    - google.com
- name: Check free disk space
  command: osDiskFreeSpace.sh
- name: Check systemd units
  command: osSystemdFailedUnits.sh
- name: Check uptime
  command: osHostRestarts.sh
- name: Check free inodes on disks
  command: osDiskFreeInodes.sh
- name: Check free memory
  command: osMemAvailable.sh
- name: Check faillock users
  command: osFaillockUser.sh
- name: Check running processes count
  command: osProcessesCount.sh
- name: Check OOM killed processes
  command: osOOMKilledProcesses.sh
- name: Check new logins
  command: osNewLogins.sh
