---
check_interval: 15m
cooldown_duration: 60m
alert_timeout: 60s
telegram_token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
telegram_chatid: 123456789
alerts:
- name: Ping google.com
  command: netPingHost.sh
  params:
    - google.com
- name: Resolve DNS-name google.com
  command: netDnsCheck.sh
  params:
    - google.com
- name: Check free disk space
  command: osDiskFreeSpace.sh
- name: Check systemd units
  command: osSystemdFailedUnits.sh
- name: Check uptime
  command: osHostRestarts.sh
- name: Check free inodes on disks
  command: osDiskFreeInodes.sh
- name: Check free memory
  command: osMemAvailable.sh
- name: Check faillock users
  command: osFaillockUser.sh
- name: Check running processes count
  command: osProcessesCount.sh
